### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by humayunjamal** [kozlice/phpfpmbeat#3]
with error

# github.com/kozlice/phpfpmbeat/beat
../go/src/github.com/kozlice/phpfpmbeat/beat/fpmbeat.go:86: b.Events undefined (type *beat.Beat has no field or method Events)
make: *** [build] Error 2

**Comment by kozlice** [comment]
@humayunjamal Looks like it's time to sync with libbeat, deps are outdated. I'll take a look at this, thanks

**Comment by kozlice** [comment]
Completely rewritten for Beats v5/v6, works now. Closing.
